import { TEAM_LIST, AWARDS_LIST, PERFORMANCE_DATA } from './common'
import { FAQS, FAQS_PRODUCTS } from './FAQ'

export const DATA = {
  TEAM_LIST,
  AWARDS_LIST,
  FAQS,
  FAQS_PRODUCTS,
  PERFORMANCE_DATA
}
