import { TEAM_LIST, AWARDS_LIST, PERFORMANCE_DATA, CONTACT_DATA, LOCATION_DATA, USER_SUPPORT_DATA } from './common'
import { FAQS, FAQS_PRODUCTS } from './FAQ'

export const DATA = {
  TEAM_LIST,
  AWARDS_LIST,
  FAQS,
  FAQS_PRODUCTS,
  PERFORMANCE_DATA,
  CONTACT_DATA,
  LOCATION_DATA,
  USER_SUPPORT_DATA
}
